# Generated by Django 4.2.7 on 2024-10-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=4000, max_length=10),
        ),
    ]
